# Generated by Django 3.2.9 on 2022-01-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_reciperequirement_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(default='default.png', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='default.png', upload_to='menu_images/%Y/%m/%d/'),
        ),
    ]
